INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:55:25] "GET / HTTP/1.1" 200 -
ERROR:controllers:Exception on /swaggerui/droid-sans.css [GET]
Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1172, in _infer_injected_bindings
    bindings = get_type_hints(callable, include_extras=True)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 1870, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Response' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_restx\api.py", line 672, in error_router
    return original_handler(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_injector\__init__.py", line 89, in wrapper
    return injector.call_with_injection(callable=fun, args=args, kwargs=kwargs)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1006, in call_with_injection
    bindings = get_bindings(callable)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1159, in get_bindings
    callable, _infer_injected_bindings(callable, only_explicit_bindings=look_for_explicit_bindings)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1174, in _infer_injected_bindings
    raise _BindingNotYetAvailable(e)
injector._BindingNotYetAvailable: name 'Response' is not defined
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:55:25] "[35m[1mGET /swaggerui/droid-sans.css HTTP/1.1[0m" 500 -
ERROR:controllers:Exception on /swaggerui/swagger-ui.css [GET]
Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1172, in _infer_injected_bindings
    bindings = get_type_hints(callable, include_extras=True)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 1870, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Response' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_restx\api.py", line 672, in error_router
    return original_handler(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_injector\__init__.py", line 89, in wrapper
    return injector.call_with_injection(callable=fun, args=args, kwargs=kwargs)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1006, in call_with_injection
    bindings = get_bindings(callable)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1159, in get_bindings
    callable, _infer_injected_bindings(callable, only_explicit_bindings=look_for_explicit_bindings)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1174, in _infer_injected_bindings
    raise _BindingNotYetAvailable(e)
injector._BindingNotYetAvailable: name 'Response' is not defined
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:55:25] "[35m[1mGET /swaggerui/swagger-ui.css HTTP/1.1[0m" 500 -
ERROR:controllers:Exception on /swaggerui/swagger-ui-standalone-preset.js [GET]
Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1172, in _infer_injected_bindings
    bindings = get_type_hints(callable, include_extras=True)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 1870, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Response' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_restx\api.py", line 672, in error_router
    return original_handler(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_injector\__init__.py", line 89, in wrapper
    return injector.call_with_injection(callable=fun, args=args, kwargs=kwargs)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1006, in call_with_injection
    bindings = get_bindings(callable)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1159, in get_bindings
    callable, _infer_injected_bindings(callable, only_explicit_bindings=look_for_explicit_bindings)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1174, in _infer_injected_bindings
    raise _BindingNotYetAvailable(e)
injector._BindingNotYetAvailable: name 'Response' is not defined
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:55:25] "[35m[1mGET /swaggerui/swagger-ui-standalone-preset.js HTTP/1.1[0m" 500 -
ERROR:controllers:Exception on /swaggerui/swagger-ui-bundle.js [GET]
Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1172, in _infer_injected_bindings
    bindings = get_type_hints(callable, include_extras=True)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 1870, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Response' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_restx\api.py", line 672, in error_router
    return original_handler(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_injector\__init__.py", line 89, in wrapper
    return injector.call_with_injection(callable=fun, args=args, kwargs=kwargs)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1006, in call_with_injection
    bindings = get_bindings(callable)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1159, in get_bindings
    callable, _infer_injected_bindings(callable, only_explicit_bindings=look_for_explicit_bindings)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1174, in _infer_injected_bindings
    raise _BindingNotYetAvailable(e)
injector._BindingNotYetAvailable: name 'Response' is not defined
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:55:25] "[35m[1mGET /swaggerui/swagger-ui-bundle.js HTTP/1.1[0m" 500 -
ERROR:controllers:Exception on /swaggerui/favicon-32x32.png [GET]
Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1172, in _infer_injected_bindings
    bindings = get_type_hints(callable, include_extras=True)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 1870, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Response' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_restx\api.py", line 672, in error_router
    return original_handler(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_injector\__init__.py", line 89, in wrapper
    return injector.call_with_injection(callable=fun, args=args, kwargs=kwargs)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1006, in call_with_injection
    bindings = get_bindings(callable)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1159, in get_bindings
    callable, _infer_injected_bindings(callable, only_explicit_bindings=look_for_explicit_bindings)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1174, in _infer_injected_bindings
    raise _BindingNotYetAvailable(e)
injector._BindingNotYetAvailable: name 'Response' is not defined
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:55:25] "[35m[1mGET /swaggerui/favicon-32x32.png HTTP/1.1[0m" 500 -
ERROR:controllers:Exception on /swaggerui/favicon-16x16.png [GET]
Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1172, in _infer_injected_bindings
    bindings = get_type_hints(callable, include_extras=True)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 1870, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Response' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_restx\api.py", line 672, in error_router
    return original_handler(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_injector\__init__.py", line 89, in wrapper
    return injector.call_with_injection(callable=fun, args=args, kwargs=kwargs)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1006, in call_with_injection
    bindings = get_bindings(callable)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1159, in get_bindings
    callable, _infer_injected_bindings(callable, only_explicit_bindings=look_for_explicit_bindings)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1174, in _infer_injected_bindings
    raise _BindingNotYetAvailable(e)
injector._BindingNotYetAvailable: name 'Response' is not defined
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:55:25] "[35m[1mGET /swaggerui/favicon-16x16.png HTTP/1.1[0m" 500 -
ERROR:controllers:Exception on /swaggerui/favicon-32x32.png [GET]
Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1172, in _infer_injected_bindings
    bindings = get_type_hints(callable, include_extras=True)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 1870, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Response' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_restx\api.py", line 672, in error_router
    return original_handler(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_injector\__init__.py", line 89, in wrapper
    return injector.call_with_injection(callable=fun, args=args, kwargs=kwargs)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1006, in call_with_injection
    bindings = get_bindings(callable)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1159, in get_bindings
    callable, _infer_injected_bindings(callable, only_explicit_bindings=look_for_explicit_bindings)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1174, in _infer_injected_bindings
    raise _BindingNotYetAvailable(e)
injector._BindingNotYetAvailable: name 'Response' is not defined
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:55:26] "[35m[1mGET /swaggerui/favicon-32x32.png HTTP/1.1[0m" 500 -
ERROR:controllers:Exception on /swaggerui/favicon-16x16.png [GET]
Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1172, in _infer_injected_bindings
    bindings = get_type_hints(callable, include_extras=True)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 1870, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Response' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_restx\api.py", line 672, in error_router
    return original_handler(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_injector\__init__.py", line 89, in wrapper
    return injector.call_with_injection(callable=fun, args=args, kwargs=kwargs)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1006, in call_with_injection
    bindings = get_bindings(callable)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1159, in get_bindings
    callable, _infer_injected_bindings(callable, only_explicit_bindings=look_for_explicit_bindings)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1174, in _infer_injected_bindings
    raise _BindingNotYetAvailable(e)
injector._BindingNotYetAvailable: name 'Response' is not defined
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:55:26] "[35m[1mGET /swaggerui/favicon-16x16.png HTTP/1.1[0m" 500 -
DEBUG:root:This message should go to the log file
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:56:52] "GET / HTTP/1.1" 200 -
ERROR:controllers:Exception on /swaggerui/droid-sans.css [GET]
Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1172, in _infer_injected_bindings
    bindings = get_type_hints(callable, include_extras=True)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 1870, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Response' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_restx\api.py", line 672, in error_router
    return original_handler(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_injector\__init__.py", line 89, in wrapper
    return injector.call_with_injection(callable=fun, args=args, kwargs=kwargs)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1006, in call_with_injection
    bindings = get_bindings(callable)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1159, in get_bindings
    callable, _infer_injected_bindings(callable, only_explicit_bindings=look_for_explicit_bindings)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1174, in _infer_injected_bindings
    raise _BindingNotYetAvailable(e)
injector._BindingNotYetAvailable: name 'Response' is not defined
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:56:52] "[35m[1mGET /swaggerui/droid-sans.css HTTP/1.1[0m" 500 -
ERROR:controllers:Exception on /swaggerui/swagger-ui.css [GET]
Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1172, in _infer_injected_bindings
    bindings = get_type_hints(callable, include_extras=True)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 1870, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Response' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_restx\api.py", line 672, in error_router
    return original_handler(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_injector\__init__.py", line 89, in wrapper
    return injector.call_with_injection(callable=fun, args=args, kwargs=kwargs)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1006, in call_with_injection
    bindings = get_bindings(callable)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1159, in get_bindings
    callable, _infer_injected_bindings(callable, only_explicit_bindings=look_for_explicit_bindings)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1174, in _infer_injected_bindings
    raise _BindingNotYetAvailable(e)
injector._BindingNotYetAvailable: name 'Response' is not defined
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:56:52] "[35m[1mGET /swaggerui/swagger-ui.css HTTP/1.1[0m" 500 -
ERROR:controllers:Exception on /swaggerui/swagger-ui-bundle.js [GET]
Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1172, in _infer_injected_bindings
    bindings = get_type_hints(callable, include_extras=True)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 1870, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Response' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_restx\api.py", line 672, in error_router
    return original_handler(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_injector\__init__.py", line 89, in wrapper
    return injector.call_with_injection(callable=fun, args=args, kwargs=kwargs)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1006, in call_with_injection
    bindings = get_bindings(callable)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1159, in get_bindings
    callable, _infer_injected_bindings(callable, only_explicit_bindings=look_for_explicit_bindings)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1174, in _infer_injected_bindings
    raise _BindingNotYetAvailable(e)
injector._BindingNotYetAvailable: name 'Response' is not defined
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:56:52] "[35m[1mGET /swaggerui/swagger-ui-bundle.js HTTP/1.1[0m" 500 -
ERROR:controllers:Exception on /swaggerui/swagger-ui-standalone-preset.js [GET]
Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1172, in _infer_injected_bindings
    bindings = get_type_hints(callable, include_extras=True)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 1870, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Response' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_restx\api.py", line 672, in error_router
    return original_handler(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_injector\__init__.py", line 89, in wrapper
    return injector.call_with_injection(callable=fun, args=args, kwargs=kwargs)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1006, in call_with_injection
    bindings = get_bindings(callable)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1159, in get_bindings
    callable, _infer_injected_bindings(callable, only_explicit_bindings=look_for_explicit_bindings)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1174, in _infer_injected_bindings
    raise _BindingNotYetAvailable(e)
injector._BindingNotYetAvailable: name 'Response' is not defined
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:56:52] "[35m[1mGET /swaggerui/swagger-ui-standalone-preset.js HTTP/1.1[0m" 500 -
ERROR:controllers:Exception on /swaggerui/favicon-32x32.png [GET]
Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1172, in _infer_injected_bindings
    bindings = get_type_hints(callable, include_extras=True)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 1870, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Response' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_restx\api.py", line 672, in error_router
    return original_handler(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_injector\__init__.py", line 89, in wrapper
    return injector.call_with_injection(callable=fun, args=args, kwargs=kwargs)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1006, in call_with_injection
    bindings = get_bindings(callable)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1159, in get_bindings
    callable, _infer_injected_bindings(callable, only_explicit_bindings=look_for_explicit_bindings)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1174, in _infer_injected_bindings
    raise _BindingNotYetAvailable(e)
injector._BindingNotYetAvailable: name 'Response' is not defined
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:56:52] "[35m[1mGET /swaggerui/favicon-32x32.png HTTP/1.1[0m" 500 -
ERROR:controllers:Exception on /swaggerui/favicon-16x16.png [GET]
Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1172, in _infer_injected_bindings
    bindings = get_type_hints(callable, include_extras=True)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 1870, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Response' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_restx\api.py", line 672, in error_router
    return original_handler(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_injector\__init__.py", line 89, in wrapper
    return injector.call_with_injection(callable=fun, args=args, kwargs=kwargs)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1006, in call_with_injection
    bindings = get_bindings(callable)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1159, in get_bindings
    callable, _infer_injected_bindings(callable, only_explicit_bindings=look_for_explicit_bindings)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1174, in _infer_injected_bindings
    raise _BindingNotYetAvailable(e)
injector._BindingNotYetAvailable: name 'Response' is not defined
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:56:52] "[35m[1mGET /swaggerui/favicon-16x16.png HTTP/1.1[0m" 500 -
ERROR:controllers:Exception on /swaggerui/favicon-32x32.png [GET]
Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1172, in _infer_injected_bindings
    bindings = get_type_hints(callable, include_extras=True)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 1870, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Response' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_restx\api.py", line 672, in error_router
    return original_handler(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_injector\__init__.py", line 89, in wrapper
    return injector.call_with_injection(callable=fun, args=args, kwargs=kwargs)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1006, in call_with_injection
    bindings = get_bindings(callable)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1159, in get_bindings
    callable, _infer_injected_bindings(callable, only_explicit_bindings=look_for_explicit_bindings)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1174, in _infer_injected_bindings
    raise _BindingNotYetAvailable(e)
injector._BindingNotYetAvailable: name 'Response' is not defined
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:56:52] "[35m[1mGET /swaggerui/favicon-32x32.png HTTP/1.1[0m" 500 -
ERROR:controllers:Exception on /swaggerui/favicon-16x16.png [GET]
Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1172, in _infer_injected_bindings
    bindings = get_type_hints(callable, include_extras=True)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 1870, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Response' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_restx\api.py", line 672, in error_router
    return original_handler(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_injector\__init__.py", line 89, in wrapper
    return injector.call_with_injection(callable=fun, args=args, kwargs=kwargs)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1006, in call_with_injection
    bindings = get_bindings(callable)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1159, in get_bindings
    callable, _infer_injected_bindings(callable, only_explicit_bindings=look_for_explicit_bindings)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1174, in _infer_injected_bindings
    raise _BindingNotYetAvailable(e)
injector._BindingNotYetAvailable: name 'Response' is not defined
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:56:52] "[35m[1mGET /swaggerui/favicon-16x16.png HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:56:53] "GET / HTTP/1.1" 200 -
ERROR:controllers:Exception on /swaggerui/droid-sans.css [GET]
Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1172, in _infer_injected_bindings
    bindings = get_type_hints(callable, include_extras=True)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 1870, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Response' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_restx\api.py", line 672, in error_router
    return original_handler(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_injector\__init__.py", line 89, in wrapper
    return injector.call_with_injection(callable=fun, args=args, kwargs=kwargs)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1006, in call_with_injection
    bindings = get_bindings(callable)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1159, in get_bindings
    callable, _infer_injected_bindings(callable, only_explicit_bindings=look_for_explicit_bindings)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1174, in _infer_injected_bindings
    raise _BindingNotYetAvailable(e)
injector._BindingNotYetAvailable: name 'Response' is not defined
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:56:53] "[35m[1mGET /swaggerui/droid-sans.css HTTP/1.1[0m" 500 -
ERROR:controllers:Exception on /swaggerui/swagger-ui.css [GET]
Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1172, in _infer_injected_bindings
    bindings = get_type_hints(callable, include_extras=True)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 1870, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Response' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_restx\api.py", line 672, in error_router
    return original_handler(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_injector\__init__.py", line 89, in wrapper
    return injector.call_with_injection(callable=fun, args=args, kwargs=kwargs)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1006, in call_with_injection
    bindings = get_bindings(callable)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1159, in get_bindings
    callable, _infer_injected_bindings(callable, only_explicit_bindings=look_for_explicit_bindings)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1174, in _infer_injected_bindings
    raise _BindingNotYetAvailable(e)
injector._BindingNotYetAvailable: name 'Response' is not defined
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:56:53] "[35m[1mGET /swaggerui/swagger-ui.css HTTP/1.1[0m" 500 -
ERROR:controllers:Exception on /swaggerui/swagger-ui-standalone-preset.js [GET]
Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1172, in _infer_injected_bindings
    bindings = get_type_hints(callable, include_extras=True)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 1870, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Response' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_restx\api.py", line 672, in error_router
    return original_handler(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_injector\__init__.py", line 89, in wrapper
    return injector.call_with_injection(callable=fun, args=args, kwargs=kwargs)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1006, in call_with_injection
    bindings = get_bindings(callable)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1159, in get_bindings
    callable, _infer_injected_bindings(callable, only_explicit_bindings=look_for_explicit_bindings)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1174, in _infer_injected_bindings
    raise _BindingNotYetAvailable(e)
injector._BindingNotYetAvailable: name 'Response' is not defined
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:56:53] "[35m[1mGET /swaggerui/swagger-ui-standalone-preset.js HTTP/1.1[0m" 500 -
ERROR:controllers:Exception on /swaggerui/swagger-ui-bundle.js [GET]
Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1172, in _infer_injected_bindings
    bindings = get_type_hints(callable, include_extras=True)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 1870, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Response' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_restx\api.py", line 672, in error_router
    return original_handler(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_injector\__init__.py", line 89, in wrapper
    return injector.call_with_injection(callable=fun, args=args, kwargs=kwargs)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1006, in call_with_injection
    bindings = get_bindings(callable)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1159, in get_bindings
    callable, _infer_injected_bindings(callable, only_explicit_bindings=look_for_explicit_bindings)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1174, in _infer_injected_bindings
    raise _BindingNotYetAvailable(e)
injector._BindingNotYetAvailable: name 'Response' is not defined
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:56:53] "[35m[1mGET /swaggerui/swagger-ui-bundle.js HTTP/1.1[0m" 500 -
ERROR:controllers:Exception on /swaggerui/favicon-32x32.png [GET]
Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1172, in _infer_injected_bindings
    bindings = get_type_hints(callable, include_extras=True)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 1870, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Response' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_restx\api.py", line 672, in error_router
    return original_handler(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_injector\__init__.py", line 89, in wrapper
    return injector.call_with_injection(callable=fun, args=args, kwargs=kwargs)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1006, in call_with_injection
    bindings = get_bindings(callable)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1159, in get_bindings
    callable, _infer_injected_bindings(callable, only_explicit_bindings=look_for_explicit_bindings)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1174, in _infer_injected_bindings
    raise _BindingNotYetAvailable(e)
injector._BindingNotYetAvailable: name 'Response' is not defined
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:56:53] "[35m[1mGET /swaggerui/favicon-32x32.png HTTP/1.1[0m" 500 -
ERROR:controllers:Exception on /swaggerui/favicon-16x16.png [GET]
Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1172, in _infer_injected_bindings
    bindings = get_type_hints(callable, include_extras=True)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 1870, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Response' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_restx\api.py", line 672, in error_router
    return original_handler(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_injector\__init__.py", line 89, in wrapper
    return injector.call_with_injection(callable=fun, args=args, kwargs=kwargs)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1006, in call_with_injection
    bindings = get_bindings(callable)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1159, in get_bindings
    callable, _infer_injected_bindings(callable, only_explicit_bindings=look_for_explicit_bindings)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1174, in _infer_injected_bindings
    raise _BindingNotYetAvailable(e)
injector._BindingNotYetAvailable: name 'Response' is not defined
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:56:53] "[35m[1mGET /swaggerui/favicon-16x16.png HTTP/1.1[0m" 500 -
ERROR:controllers:Exception on /swaggerui/favicon-32x32.png [GET]
Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1172, in _infer_injected_bindings
    bindings = get_type_hints(callable, include_extras=True)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 1870, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Response' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_restx\api.py", line 672, in error_router
    return original_handler(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_injector\__init__.py", line 89, in wrapper
    return injector.call_with_injection(callable=fun, args=args, kwargs=kwargs)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1006, in call_with_injection
    bindings = get_bindings(callable)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1159, in get_bindings
    callable, _infer_injected_bindings(callable, only_explicit_bindings=look_for_explicit_bindings)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1174, in _infer_injected_bindings
    raise _BindingNotYetAvailable(e)
injector._BindingNotYetAvailable: name 'Response' is not defined
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:56:53] "[35m[1mGET /swaggerui/favicon-32x32.png HTTP/1.1[0m" 500 -
ERROR:controllers:Exception on /swaggerui/favicon-16x16.png [GET]
Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1172, in _infer_injected_bindings
    bindings = get_type_hints(callable, include_extras=True)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 1870, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Response' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_restx\api.py", line 672, in error_router
    return original_handler(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_injector\__init__.py", line 89, in wrapper
    return injector.call_with_injection(callable=fun, args=args, kwargs=kwargs)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1006, in call_with_injection
    bindings = get_bindings(callable)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1159, in get_bindings
    callable, _infer_injected_bindings(callable, only_explicit_bindings=look_for_explicit_bindings)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1174, in _infer_injected_bindings
    raise _BindingNotYetAvailable(e)
injector._BindingNotYetAvailable: name 'Response' is not defined
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:56:53] "[35m[1mGET /swaggerui/favicon-16x16.png HTTP/1.1[0m" 500 -
DEBUG:root:This message should go to the log file
DEBUG:root:This message should go to the log file
DEBUG:root:This message should go to the log file
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:05:46] "GET / HTTP/1.1" 200 -
ERROR:controllers:Exception on /swaggerui/droid-sans.css [GET]
Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1172, in _infer_injected_bindings
    bindings = get_type_hints(callable, include_extras=True)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 1870, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Response' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_restx\api.py", line 672, in error_router
    return original_handler(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_injector\__init__.py", line 89, in wrapper
    return injector.call_with_injection(callable=fun, args=args, kwargs=kwargs)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1006, in call_with_injection
    bindings = get_bindings(callable)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1159, in get_bindings
    callable, _infer_injected_bindings(callable, only_explicit_bindings=look_for_explicit_bindings)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1174, in _infer_injected_bindings
    raise _BindingNotYetAvailable(e)
injector._BindingNotYetAvailable: name 'Response' is not defined
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:05:46] "[35m[1mGET /swaggerui/droid-sans.css HTTP/1.1[0m" 500 -
ERROR:controllers:Exception on /swaggerui/swagger-ui.css [GET]
Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1172, in _infer_injected_bindings
    bindings = get_type_hints(callable, include_extras=True)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 1870, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Response' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_restx\api.py", line 672, in error_router
    return original_handler(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_injector\__init__.py", line 89, in wrapper
    return injector.call_with_injection(callable=fun, args=args, kwargs=kwargs)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1006, in call_with_injection
    bindings = get_bindings(callable)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1159, in get_bindings
    callable, _infer_injected_bindings(callable, only_explicit_bindings=look_for_explicit_bindings)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1174, in _infer_injected_bindings
    raise _BindingNotYetAvailable(e)
injector._BindingNotYetAvailable: name 'Response' is not defined
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:05:46] "[35m[1mGET /swaggerui/swagger-ui.css HTTP/1.1[0m" 500 -
ERROR:controllers:Exception on /swaggerui/swagger-ui-bundle.js [GET]
Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1172, in _infer_injected_bindings
    bindings = get_type_hints(callable, include_extras=True)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 1870, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Response' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_restx\api.py", line 672, in error_router
    return original_handler(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_injector\__init__.py", line 89, in wrapper
    return injector.call_with_injection(callable=fun, args=args, kwargs=kwargs)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1006, in call_with_injection
    bindings = get_bindings(callable)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1159, in get_bindings
    callable, _infer_injected_bindings(callable, only_explicit_bindings=look_for_explicit_bindings)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1174, in _infer_injected_bindings
    raise _BindingNotYetAvailable(e)
injector._BindingNotYetAvailable: name 'Response' is not defined
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:05:46] "[35m[1mGET /swaggerui/swagger-ui-bundle.js HTTP/1.1[0m" 500 -
ERROR:controllers:Exception on /swaggerui/swagger-ui-standalone-preset.js [GET]
Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1172, in _infer_injected_bindings
    bindings = get_type_hints(callable, include_extras=True)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 1870, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Response' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_restx\api.py", line 672, in error_router
    return original_handler(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_injector\__init__.py", line 89, in wrapper
    return injector.call_with_injection(callable=fun, args=args, kwargs=kwargs)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1006, in call_with_injection
    bindings = get_bindings(callable)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1159, in get_bindings
    callable, _infer_injected_bindings(callable, only_explicit_bindings=look_for_explicit_bindings)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1174, in _infer_injected_bindings
    raise _BindingNotYetAvailable(e)
injector._BindingNotYetAvailable: name 'Response' is not defined
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:05:46] "[35m[1mGET /swaggerui/swagger-ui-standalone-preset.js HTTP/1.1[0m" 500 -
ERROR:controllers:Exception on /swaggerui/favicon-32x32.png [GET]
Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1172, in _infer_injected_bindings
    bindings = get_type_hints(callable, include_extras=True)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 1870, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Response' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_restx\api.py", line 672, in error_router
    return original_handler(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_injector\__init__.py", line 89, in wrapper
    return injector.call_with_injection(callable=fun, args=args, kwargs=kwargs)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1006, in call_with_injection
    bindings = get_bindings(callable)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1159, in get_bindings
    callable, _infer_injected_bindings(callable, only_explicit_bindings=look_for_explicit_bindings)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1174, in _infer_injected_bindings
    raise _BindingNotYetAvailable(e)
injector._BindingNotYetAvailable: name 'Response' is not defined
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:05:46] "[35m[1mGET /swaggerui/favicon-32x32.png HTTP/1.1[0m" 500 -
ERROR:controllers:Exception on /swaggerui/favicon-16x16.png [GET]
Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1172, in _infer_injected_bindings
    bindings = get_type_hints(callable, include_extras=True)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 1870, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Response' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_restx\api.py", line 672, in error_router
    return original_handler(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_injector\__init__.py", line 89, in wrapper
    return injector.call_with_injection(callable=fun, args=args, kwargs=kwargs)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1006, in call_with_injection
    bindings = get_bindings(callable)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1159, in get_bindings
    callable, _infer_injected_bindings(callable, only_explicit_bindings=look_for_explicit_bindings)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1174, in _infer_injected_bindings
    raise _BindingNotYetAvailable(e)
injector._BindingNotYetAvailable: name 'Response' is not defined
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:05:46] "[35m[1mGET /swaggerui/favicon-16x16.png HTTP/1.1[0m" 500 -
ERROR:controllers:Exception on /swaggerui/favicon-32x32.png [GET]
Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1172, in _infer_injected_bindings
    bindings = get_type_hints(callable, include_extras=True)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 1870, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Response' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_restx\api.py", line 672, in error_router
    return original_handler(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_injector\__init__.py", line 89, in wrapper
    return injector.call_with_injection(callable=fun, args=args, kwargs=kwargs)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1006, in call_with_injection
    bindings = get_bindings(callable)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1159, in get_bindings
    callable, _infer_injected_bindings(callable, only_explicit_bindings=look_for_explicit_bindings)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1174, in _infer_injected_bindings
    raise _BindingNotYetAvailable(e)
injector._BindingNotYetAvailable: name 'Response' is not defined
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:05:46] "[35m[1mGET /swaggerui/favicon-32x32.png HTTP/1.1[0m" 500 -
ERROR:controllers:Exception on /swaggerui/favicon-16x16.png [GET]
Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1172, in _infer_injected_bindings
    bindings = get_type_hints(callable, include_extras=True)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 1870, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Response' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_restx\api.py", line 672, in error_router
    return original_handler(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_injector\__init__.py", line 89, in wrapper
    return injector.call_with_injection(callable=fun, args=args, kwargs=kwargs)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1006, in call_with_injection
    bindings = get_bindings(callable)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1159, in get_bindings
    callable, _infer_injected_bindings(callable, only_explicit_bindings=look_for_explicit_bindings)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1174, in _infer_injected_bindings
    raise _BindingNotYetAvailable(e)
injector._BindingNotYetAvailable: name 'Response' is not defined
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:05:46] "[35m[1mGET /swaggerui/favicon-16x16.png HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:05:47] "GET / HTTP/1.1" 200 -
ERROR:controllers:Exception on /swaggerui/droid-sans.css [GET]
Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1172, in _infer_injected_bindings
    bindings = get_type_hints(callable, include_extras=True)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 1870, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Response' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_restx\api.py", line 672, in error_router
    return original_handler(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_injector\__init__.py", line 89, in wrapper
    return injector.call_with_injection(callable=fun, args=args, kwargs=kwargs)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1006, in call_with_injection
    bindings = get_bindings(callable)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1159, in get_bindings
    callable, _infer_injected_bindings(callable, only_explicit_bindings=look_for_explicit_bindings)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1174, in _infer_injected_bindings
    raise _BindingNotYetAvailable(e)
injector._BindingNotYetAvailable: name 'Response' is not defined
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:05:47] "[35m[1mGET /swaggerui/droid-sans.css HTTP/1.1[0m" 500 -
ERROR:controllers:Exception on /swaggerui/swagger-ui.css [GET]
Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1172, in _infer_injected_bindings
    bindings = get_type_hints(callable, include_extras=True)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 1870, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Response' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_restx\api.py", line 672, in error_router
    return original_handler(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_injector\__init__.py", line 89, in wrapper
    return injector.call_with_injection(callable=fun, args=args, kwargs=kwargs)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1006, in call_with_injection
    bindings = get_bindings(callable)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1159, in get_bindings
    callable, _infer_injected_bindings(callable, only_explicit_bindings=look_for_explicit_bindings)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1174, in _infer_injected_bindings
    raise _BindingNotYetAvailable(e)
injector._BindingNotYetAvailable: name 'Response' is not defined
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:05:47] "[35m[1mGET /swaggerui/swagger-ui.css HTTP/1.1[0m" 500 -
ERROR:controllers:Exception on /swaggerui/swagger-ui-bundle.js [GET]
Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1172, in _infer_injected_bindings
    bindings = get_type_hints(callable, include_extras=True)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 1870, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Response' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_restx\api.py", line 672, in error_router
    return original_handler(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_injector\__init__.py", line 89, in wrapper
    return injector.call_with_injection(callable=fun, args=args, kwargs=kwargs)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1006, in call_with_injection
    bindings = get_bindings(callable)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1159, in get_bindings
    callable, _infer_injected_bindings(callable, only_explicit_bindings=look_for_explicit_bindings)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1174, in _infer_injected_bindings
    raise _BindingNotYetAvailable(e)
injector._BindingNotYetAvailable: name 'Response' is not defined
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:05:47] "[35m[1mGET /swaggerui/swagger-ui-bundle.js HTTP/1.1[0m" 500 -
ERROR:controllers:Exception on /swaggerui/swagger-ui-standalone-preset.js [GET]
Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1172, in _infer_injected_bindings
    bindings = get_type_hints(callable, include_extras=True)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 1870, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Response' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_restx\api.py", line 672, in error_router
    return original_handler(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_injector\__init__.py", line 89, in wrapper
    return injector.call_with_injection(callable=fun, args=args, kwargs=kwargs)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1006, in call_with_injection
    bindings = get_bindings(callable)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1159, in get_bindings
    callable, _infer_injected_bindings(callable, only_explicit_bindings=look_for_explicit_bindings)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1174, in _infer_injected_bindings
    raise _BindingNotYetAvailable(e)
injector._BindingNotYetAvailable: name 'Response' is not defined
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:05:47] "[35m[1mGET /swaggerui/swagger-ui-standalone-preset.js HTTP/1.1[0m" 500 -
ERROR:controllers:Exception on /swaggerui/favicon-32x32.png [GET]
Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1172, in _infer_injected_bindings
    bindings = get_type_hints(callable, include_extras=True)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 1870, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Response' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_restx\api.py", line 672, in error_router
    return original_handler(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_injector\__init__.py", line 89, in wrapper
    return injector.call_with_injection(callable=fun, args=args, kwargs=kwargs)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1006, in call_with_injection
    bindings = get_bindings(callable)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1159, in get_bindings
    callable, _infer_injected_bindings(callable, only_explicit_bindings=look_for_explicit_bindings)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1174, in _infer_injected_bindings
    raise _BindingNotYetAvailable(e)
injector._BindingNotYetAvailable: name 'Response' is not defined
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:05:47] "[35m[1mGET /swaggerui/favicon-32x32.png HTTP/1.1[0m" 500 -
ERROR:controllers:Exception on /swaggerui/favicon-16x16.png [GET]
Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1172, in _infer_injected_bindings
    bindings = get_type_hints(callable, include_extras=True)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 1870, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Response' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_restx\api.py", line 672, in error_router
    return original_handler(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_injector\__init__.py", line 89, in wrapper
    return injector.call_with_injection(callable=fun, args=args, kwargs=kwargs)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1006, in call_with_injection
    bindings = get_bindings(callable)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1159, in get_bindings
    callable, _infer_injected_bindings(callable, only_explicit_bindings=look_for_explicit_bindings)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1174, in _infer_injected_bindings
    raise _BindingNotYetAvailable(e)
injector._BindingNotYetAvailable: name 'Response' is not defined
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:05:47] "[35m[1mGET /swaggerui/favicon-16x16.png HTTP/1.1[0m" 500 -
ERROR:controllers:Exception on /swaggerui/favicon-32x32.png [GET]
Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1172, in _infer_injected_bindings
    bindings = get_type_hints(callable, include_extras=True)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 1870, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Response' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_restx\api.py", line 672, in error_router
    return original_handler(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_injector\__init__.py", line 89, in wrapper
    return injector.call_with_injection(callable=fun, args=args, kwargs=kwargs)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1006, in call_with_injection
    bindings = get_bindings(callable)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1159, in get_bindings
    callable, _infer_injected_bindings(callable, only_explicit_bindings=look_for_explicit_bindings)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1174, in _infer_injected_bindings
    raise _BindingNotYetAvailable(e)
injector._BindingNotYetAvailable: name 'Response' is not defined
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:05:47] "[35m[1mGET /swaggerui/favicon-32x32.png HTTP/1.1[0m" 500 -
ERROR:controllers:Exception on /swaggerui/favicon-16x16.png [GET]
Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1172, in _infer_injected_bindings
    bindings = get_type_hints(callable, include_extras=True)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 1870, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Response' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_restx\api.py", line 672, in error_router
    return original_handler(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_injector\__init__.py", line 89, in wrapper
    return injector.call_with_injection(callable=fun, args=args, kwargs=kwargs)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1006, in call_with_injection
    bindings = get_bindings(callable)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1159, in get_bindings
    callable, _infer_injected_bindings(callable, only_explicit_bindings=look_for_explicit_bindings)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1174, in _infer_injected_bindings
    raise _BindingNotYetAvailable(e)
injector._BindingNotYetAvailable: name 'Response' is not defined
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:05:47] "[35m[1mGET /swaggerui/favicon-16x16.png HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:05:48] "GET / HTTP/1.1" 200 -
ERROR:controllers:Exception on /swaggerui/droid-sans.css [GET]
Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1172, in _infer_injected_bindings
    bindings = get_type_hints(callable, include_extras=True)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 1870, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Response' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_restx\api.py", line 672, in error_router
    return original_handler(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_injector\__init__.py", line 89, in wrapper
    return injector.call_with_injection(callable=fun, args=args, kwargs=kwargs)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1006, in call_with_injection
    bindings = get_bindings(callable)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1159, in get_bindings
    callable, _infer_injected_bindings(callable, only_explicit_bindings=look_for_explicit_bindings)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1174, in _infer_injected_bindings
    raise _BindingNotYetAvailable(e)
injector._BindingNotYetAvailable: name 'Response' is not defined
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:05:48] "[35m[1mGET /swaggerui/droid-sans.css HTTP/1.1[0m" 500 -
ERROR:controllers:Exception on /swaggerui/swagger-ui.css [GET]
Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1172, in _infer_injected_bindings
    bindings = get_type_hints(callable, include_extras=True)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 1870, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Response' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_restx\api.py", line 672, in error_router
    return original_handler(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_injector\__init__.py", line 89, in wrapper
    return injector.call_with_injection(callable=fun, args=args, kwargs=kwargs)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1006, in call_with_injection
    bindings = get_bindings(callable)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1159, in get_bindings
    callable, _infer_injected_bindings(callable, only_explicit_bindings=look_for_explicit_bindings)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1174, in _infer_injected_bindings
    raise _BindingNotYetAvailable(e)
injector._BindingNotYetAvailable: name 'Response' is not defined
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:05:48] "[35m[1mGET /swaggerui/swagger-ui.css HTTP/1.1[0m" 500 -
ERROR:controllers:Exception on /swaggerui/swagger-ui-bundle.js [GET]
Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1172, in _infer_injected_bindings
    bindings = get_type_hints(callable, include_extras=True)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 1870, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Response' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_restx\api.py", line 672, in error_router
    return original_handler(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_injector\__init__.py", line 89, in wrapper
    return injector.call_with_injection(callable=fun, args=args, kwargs=kwargs)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1006, in call_with_injection
    bindings = get_bindings(callable)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1159, in get_bindings
    callable, _infer_injected_bindings(callable, only_explicit_bindings=look_for_explicit_bindings)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1174, in _infer_injected_bindings
    raise _BindingNotYetAvailable(e)
injector._BindingNotYetAvailable: name 'Response' is not defined
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:05:48] "[35m[1mGET /swaggerui/swagger-ui-bundle.js HTTP/1.1[0m" 500 -
ERROR:controllers:Exception on /swaggerui/swagger-ui-standalone-preset.js [GET]
Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1172, in _infer_injected_bindings
    bindings = get_type_hints(callable, include_extras=True)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 1870, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Response' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_restx\api.py", line 672, in error_router
    return original_handler(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_injector\__init__.py", line 89, in wrapper
    return injector.call_with_injection(callable=fun, args=args, kwargs=kwargs)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1006, in call_with_injection
    bindings = get_bindings(callable)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1159, in get_bindings
    callable, _infer_injected_bindings(callable, only_explicit_bindings=look_for_explicit_bindings)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1174, in _infer_injected_bindings
    raise _BindingNotYetAvailable(e)
injector._BindingNotYetAvailable: name 'Response' is not defined
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:05:48] "[35m[1mGET /swaggerui/swagger-ui-standalone-preset.js HTTP/1.1[0m" 500 -
ERROR:controllers:Exception on /swaggerui/favicon-32x32.png [GET]
Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1172, in _infer_injected_bindings
    bindings = get_type_hints(callable, include_extras=True)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 1870, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Response' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_restx\api.py", line 672, in error_router
    return original_handler(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_injector\__init__.py", line 89, in wrapper
    return injector.call_with_injection(callable=fun, args=args, kwargs=kwargs)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1006, in call_with_injection
    bindings = get_bindings(callable)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1159, in get_bindings
    callable, _infer_injected_bindings(callable, only_explicit_bindings=look_for_explicit_bindings)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1174, in _infer_injected_bindings
    raise _BindingNotYetAvailable(e)
injector._BindingNotYetAvailable: name 'Response' is not defined
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:05:48] "[35m[1mGET /swaggerui/favicon-32x32.png HTTP/1.1[0m" 500 -
ERROR:controllers:Exception on /swaggerui/favicon-16x16.png [GET]
Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1172, in _infer_injected_bindings
    bindings = get_type_hints(callable, include_extras=True)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 1870, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Response' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_restx\api.py", line 672, in error_router
    return original_handler(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_injector\__init__.py", line 89, in wrapper
    return injector.call_with_injection(callable=fun, args=args, kwargs=kwargs)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1006, in call_with_injection
    bindings = get_bindings(callable)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1159, in get_bindings
    callable, _infer_injected_bindings(callable, only_explicit_bindings=look_for_explicit_bindings)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1174, in _infer_injected_bindings
    raise _BindingNotYetAvailable(e)
injector._BindingNotYetAvailable: name 'Response' is not defined
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:05:48] "[35m[1mGET /swaggerui/favicon-16x16.png HTTP/1.1[0m" 500 -
ERROR:controllers:Exception on /swaggerui/favicon-32x32.png [GET]
Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1172, in _infer_injected_bindings
    bindings = get_type_hints(callable, include_extras=True)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 1870, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Response' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_restx\api.py", line 672, in error_router
    return original_handler(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_injector\__init__.py", line 89, in wrapper
    return injector.call_with_injection(callable=fun, args=args, kwargs=kwargs)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1006, in call_with_injection
    bindings = get_bindings(callable)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1159, in get_bindings
    callable, _infer_injected_bindings(callable, only_explicit_bindings=look_for_explicit_bindings)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1174, in _infer_injected_bindings
    raise _BindingNotYetAvailable(e)
injector._BindingNotYetAvailable: name 'Response' is not defined
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:05:48] "[35m[1mGET /swaggerui/favicon-32x32.png HTTP/1.1[0m" 500 -
ERROR:controllers:Exception on /swaggerui/favicon-16x16.png [GET]
Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1172, in _infer_injected_bindings
    bindings = get_type_hints(callable, include_extras=True)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 1870, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Response' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_restx\api.py", line 672, in error_router
    return original_handler(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_injector\__init__.py", line 89, in wrapper
    return injector.call_with_injection(callable=fun, args=args, kwargs=kwargs)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1006, in call_with_injection
    bindings = get_bindings(callable)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1159, in get_bindings
    callable, _infer_injected_bindings(callable, only_explicit_bindings=look_for_explicit_bindings)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1174, in _infer_injected_bindings
    raise _BindingNotYetAvailable(e)
injector._BindingNotYetAvailable: name 'Response' is not defined
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:05:48] "[35m[1mGET /swaggerui/favicon-16x16.png HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:05:48] "GET / HTTP/1.1" 200 -
ERROR:controllers:Exception on /swaggerui/droid-sans.css [GET]
Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1172, in _infer_injected_bindings
    bindings = get_type_hints(callable, include_extras=True)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 1870, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Response' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_restx\api.py", line 672, in error_router
    return original_handler(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_injector\__init__.py", line 89, in wrapper
    return injector.call_with_injection(callable=fun, args=args, kwargs=kwargs)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1006, in call_with_injection
    bindings = get_bindings(callable)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1159, in get_bindings
    callable, _infer_injected_bindings(callable, only_explicit_bindings=look_for_explicit_bindings)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1174, in _infer_injected_bindings
    raise _BindingNotYetAvailable(e)
injector._BindingNotYetAvailable: name 'Response' is not defined
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:05:48] "[35m[1mGET /swaggerui/droid-sans.css HTTP/1.1[0m" 500 -
ERROR:controllers:Exception on /swaggerui/swagger-ui.css [GET]
Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1172, in _infer_injected_bindings
    bindings = get_type_hints(callable, include_extras=True)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 1870, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Response' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_restx\api.py", line 672, in error_router
    return original_handler(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_injector\__init__.py", line 89, in wrapper
    return injector.call_with_injection(callable=fun, args=args, kwargs=kwargs)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1006, in call_with_injection
    bindings = get_bindings(callable)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1159, in get_bindings
    callable, _infer_injected_bindings(callable, only_explicit_bindings=look_for_explicit_bindings)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1174, in _infer_injected_bindings
    raise _BindingNotYetAvailable(e)
injector._BindingNotYetAvailable: name 'Response' is not defined
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:05:49] "[35m[1mGET /swaggerui/swagger-ui.css HTTP/1.1[0m" 500 -
ERROR:controllers:Exception on /swaggerui/swagger-ui-bundle.js [GET]
Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1172, in _infer_injected_bindings
    bindings = get_type_hints(callable, include_extras=True)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 1870, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Response' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_restx\api.py", line 672, in error_router
    return original_handler(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_injector\__init__.py", line 89, in wrapper
    return injector.call_with_injection(callable=fun, args=args, kwargs=kwargs)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1006, in call_with_injection
    bindings = get_bindings(callable)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1159, in get_bindings
    callable, _infer_injected_bindings(callable, only_explicit_bindings=look_for_explicit_bindings)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1174, in _infer_injected_bindings
    raise _BindingNotYetAvailable(e)
injector._BindingNotYetAvailable: name 'Response' is not defined
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:05:49] "[35m[1mGET /swaggerui/swagger-ui-bundle.js HTTP/1.1[0m" 500 -
ERROR:controllers:Exception on /swaggerui/swagger-ui-standalone-preset.js [GET]
Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1172, in _infer_injected_bindings
    bindings = get_type_hints(callable, include_extras=True)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 1870, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Response' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_restx\api.py", line 672, in error_router
    return original_handler(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_injector\__init__.py", line 89, in wrapper
    return injector.call_with_injection(callable=fun, args=args, kwargs=kwargs)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1006, in call_with_injection
    bindings = get_bindings(callable)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1159, in get_bindings
    callable, _infer_injected_bindings(callable, only_explicit_bindings=look_for_explicit_bindings)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1174, in _infer_injected_bindings
    raise _BindingNotYetAvailable(e)
injector._BindingNotYetAvailable: name 'Response' is not defined
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:05:49] "[35m[1mGET /swaggerui/swagger-ui-standalone-preset.js HTTP/1.1[0m" 500 -
ERROR:controllers:Exception on /swaggerui/favicon-32x32.png [GET]
Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1172, in _infer_injected_bindings
    bindings = get_type_hints(callable, include_extras=True)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 1870, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Response' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_restx\api.py", line 672, in error_router
    return original_handler(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_injector\__init__.py", line 89, in wrapper
    return injector.call_with_injection(callable=fun, args=args, kwargs=kwargs)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1006, in call_with_injection
    bindings = get_bindings(callable)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1159, in get_bindings
    callable, _infer_injected_bindings(callable, only_explicit_bindings=look_for_explicit_bindings)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1174, in _infer_injected_bindings
    raise _BindingNotYetAvailable(e)
injector._BindingNotYetAvailable: name 'Response' is not defined
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:05:49] "[35m[1mGET /swaggerui/favicon-32x32.png HTTP/1.1[0m" 500 -
ERROR:controllers:Exception on /swaggerui/favicon-16x16.png [GET]
Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1172, in _infer_injected_bindings
    bindings = get_type_hints(callable, include_extras=True)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 1870, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Response' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_restx\api.py", line 672, in error_router
    return original_handler(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_injector\__init__.py", line 89, in wrapper
    return injector.call_with_injection(callable=fun, args=args, kwargs=kwargs)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1006, in call_with_injection
    bindings = get_bindings(callable)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1159, in get_bindings
    callable, _infer_injected_bindings(callable, only_explicit_bindings=look_for_explicit_bindings)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1174, in _infer_injected_bindings
    raise _BindingNotYetAvailable(e)
injector._BindingNotYetAvailable: name 'Response' is not defined
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:05:49] "[35m[1mGET /swaggerui/favicon-16x16.png HTTP/1.1[0m" 500 -
ERROR:controllers:Exception on /swaggerui/favicon-32x32.png [GET]
Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1172, in _infer_injected_bindings
    bindings = get_type_hints(callable, include_extras=True)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 1870, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Response' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_restx\api.py", line 672, in error_router
    return original_handler(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_injector\__init__.py", line 89, in wrapper
    return injector.call_with_injection(callable=fun, args=args, kwargs=kwargs)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1006, in call_with_injection
    bindings = get_bindings(callable)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1159, in get_bindings
    callable, _infer_injected_bindings(callable, only_explicit_bindings=look_for_explicit_bindings)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1174, in _infer_injected_bindings
    raise _BindingNotYetAvailable(e)
injector._BindingNotYetAvailable: name 'Response' is not defined
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:05:49] "[35m[1mGET /swaggerui/favicon-32x32.png HTTP/1.1[0m" 500 -
ERROR:controllers:Exception on /swaggerui/favicon-16x16.png [GET]
Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1172, in _infer_injected_bindings
    bindings = get_type_hints(callable, include_extras=True)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 1870, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Response' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_restx\api.py", line 672, in error_router
    return original_handler(e)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_injector\__init__.py", line 89, in wrapper
    return injector.call_with_injection(callable=fun, args=args, kwargs=kwargs)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1006, in call_with_injection
    bindings = get_bindings(callable)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1159, in get_bindings
    callable, _infer_injected_bindings(callable, only_explicit_bindings=look_for_explicit_bindings)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python310\lib\site-packages\injector\__init__.py", line 1174, in _infer_injected_bindings
    raise _BindingNotYetAvailable(e)
injector._BindingNotYetAvailable: name 'Response' is not defined
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:05:49] "[35m[1mGET /swaggerui/favicon-16x16.png HTTP/1.1[0m" 500 -
DEBUG:root:This message should go to the log file
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:werkzeug: * Restarting with stat
DEBUG:root:This message should go to the log file
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:08:06] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:08:06] "[35m[1mGET /swaggerui/swagger-ui.css HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:08:06] "[35m[1mGET /swaggerui/droid-sans.css HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:08:06] "[35m[1mGET /swaggerui/swagger-ui-bundle.js HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:08:06] "[35m[1mGET /swaggerui/swagger-ui-standalone-preset.js HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:08:06] "[35m[1mGET /swaggerui/favicon-32x32.png HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:08:06] "[35m[1mGET /swaggerui/favicon-16x16.png HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:08:06] "[35m[1mGET /swaggerui/favicon-32x32.png HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:08:06] "[35m[1mGET /swaggerui/favicon-16x16.png HTTP/1.1[0m" 500 -
DEBUG:root:This message should go to the log file
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:werkzeug: * Restarting with stat
DEBUG:root:This message should go to the log file
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:10:06] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:10:07] "[35m[1mGET /swaggerui/swagger-ui.css HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:10:07] "[35m[1mGET /swaggerui/droid-sans.css HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:10:07] "[35m[1mGET /swaggerui/swagger-ui-standalone-preset.js HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:10:07] "[35m[1mGET /swaggerui/swagger-ui-bundle.js HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:10:07] "[35m[1mGET /swaggerui/favicon-32x32.png HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:10:07] "[35m[1mGET /swaggerui/favicon-16x16.png HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:10:07] "[35m[1mGET /swaggerui/favicon-32x32.png HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:10:07] "[35m[1mGET /swaggerui/favicon-16x16.png HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:10:08] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:10:08] "[35m[1mGET /swaggerui/droid-sans.css HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:10:08] "[35m[1mGET /swaggerui/swagger-ui-bundle.js HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:10:08] "[35m[1mGET /swaggerui/swagger-ui.css HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:10:08] "[35m[1mGET /swaggerui/swagger-ui-standalone-preset.js HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:10:08] "[35m[1mGET /swaggerui/favicon-32x32.png HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:10:08] "[35m[1mGET /swaggerui/favicon-16x16.png HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:10:08] "[35m[1mGET /swaggerui/favicon-32x32.png HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:10:09] "[35m[1mGET /swaggerui/favicon-16x16.png HTTP/1.1[0m" 500 -
DEBUG:root:This message should go to the log file
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:werkzeug: * Restarting with stat
DEBUG:root:This message should go to the log file
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:11:09] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:11:09] "[35m[1mGET /swaggerui/swagger-ui-bundle.js HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:11:09] "[35m[1mGET /swaggerui/swagger-ui.css HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:11:09] "[35m[1mGET /swaggerui/droid-sans.css HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:11:09] "[35m[1mGET /swaggerui/swagger-ui-standalone-preset.js HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:11:09] "[35m[1mGET /swaggerui/favicon-32x32.png HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:11:09] "[35m[1mGET /swaggerui/favicon-16x16.png HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:11:10] "[35m[1mGET /swaggerui/favicon-32x32.png HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:11:10] "[35m[1mGET /swaggerui/favicon-16x16.png HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:11:10] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:11:11] "[35m[1mGET /swaggerui/swagger-ui-bundle.js HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:11:11] "[35m[1mGET /swaggerui/swagger-ui-standalone-preset.js HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:11:11] "[35m[1mGET /swaggerui/droid-sans.css HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:11:11] "[35m[1mGET /swaggerui/swagger-ui.css HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:11:11] "[35m[1mGET /swaggerui/favicon-32x32.png HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:11:11] "[35m[1mGET /swaggerui/favicon-16x16.png HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:11:11] "[35m[1mGET /swaggerui/favicon-32x32.png HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:11:11] "[35m[1mGET /swaggerui/favicon-16x16.png HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:11:15] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:11:16] "[35m[1mGET /swaggerui/swagger-ui-standalone-preset.js HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:11:16] "[35m[1mGET /swaggerui/swagger-ui.css HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:11:16] "[35m[1mGET /swaggerui/swagger-ui-bundle.js HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:11:16] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:11:16] "[35m[1mGET /swaggerui/droid-sans.css HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:11:16] "[35m[1mGET /swaggerui/swagger-ui-bundle.js HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:11:16] "[35m[1mGET /swaggerui/swagger-ui.css HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:11:16] "[35m[1mGET /swaggerui/droid-sans.css HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:11:16] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:11:16] "[35m[1mGET /swaggerui/swagger-ui-standalone-preset.js HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:11:16] "[35m[1mGET /swaggerui/swagger-ui-standalone-preset.js HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:11:16] "[35m[1mGET /swaggerui/swagger-ui.css HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:11:16] "[35m[1mGET /swaggerui/droid-sans.css HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:11:16] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:11:16] "[35m[1mGET /swaggerui/swagger-ui-bundle.js HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:11:16] "[35m[1mGET /swaggerui/swagger-ui-standalone-preset.js HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:11:16] "[35m[1mGET /swaggerui/swagger-ui-bundle.js HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:11:16] "[35m[1mGET /swaggerui/droid-sans.css HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:11:16] "[35m[1mGET /swaggerui/swagger-ui.css HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:11:16] "[35m[1mGET /swaggerui/favicon-32x32.png HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:11:17] "[35m[1mGET /swaggerui/favicon-16x16.png HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:11:17] "[35m[1mGET /swaggerui/favicon-32x32.png HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:11:17] "[35m[1mGET /swaggerui/favicon-16x16.png HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:11:18] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:11:18] "[35m[1mGET /swaggerui/swagger-ui.css HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:11:18] "[35m[1mGET /swaggerui/swagger-ui-bundle.js HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:11:18] "[35m[1mGET /swaggerui/droid-sans.css HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:11:18] "[35m[1mGET /swaggerui/swagger-ui-standalone-preset.js HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:11:18] "[35m[1mGET /swaggerui/favicon-32x32.png HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:11:18] "[35m[1mGET /swaggerui/favicon-16x16.png HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:11:18] "[35m[1mGET /swaggerui/favicon-32x32.png HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:11:18] "[35m[1mGET /swaggerui/favicon-16x16.png HTTP/1.1[0m" 500 -
DEBUG:root:This message should go to the log file
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:werkzeug: * Restarting with stat
DEBUG:root:This message should go to the log file
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:13:51] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:13:51] "[35m[1mGET /swaggerui/swagger-ui.css HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:13:51] "[35m[1mGET /swaggerui/swagger-ui-bundle.js HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:13:51] "[35m[1mGET /swaggerui/swagger-ui-standalone-preset.js HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:13:51] "[35m[1mGET /swaggerui/droid-sans.css HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:13:51] "[35m[1mGET /swaggerui/favicon-32x32.png HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:13:51] "[35m[1mGET /swaggerui/favicon-16x16.png HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:13:51] "[35m[1mGET /swaggerui/favicon-32x32.png HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:13:51] "[35m[1mGET /swaggerui/favicon-16x16.png HTTP/1.1[0m" 500 -
DEBUG:root:This message should go to the log file
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:werkzeug: * Restarting with stat
DEBUG:root:This message should go to the log file
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:15:41] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:15:41] "[35m[1mGET /swaggerui/swagger-ui-bundle.js HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:15:41] "[35m[1mGET /swaggerui/swagger-ui-standalone-preset.js HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:15:41] "[35m[1mGET /swaggerui/swagger-ui.css HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:15:41] "[35m[1mGET /swaggerui/droid-sans.css HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:15:41] "[35m[1mGET /swaggerui/favicon-32x32.png HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:15:41] "[35m[1mGET /swaggerui/favicon-16x16.png HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:15:41] "[35m[1mGET /swaggerui/favicon-32x32.png HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:15:41] "[35m[1mGET /swaggerui/favicon-16x16.png HTTP/1.1[0m" 500 -
DEBUG:root:This message should go to the log file
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:werkzeug: * Restarting with stat
DEBUG:root:This message should go to the log file
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 10:07:59] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 10:07:59] "[35m[1mGET /swaggerui/droid-sans.css HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 10:07:59] "[35m[1mGET /swaggerui/swagger-ui.css HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 10:07:59] "[35m[1mGET /swaggerui/swagger-ui-bundle.js HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 10:07:59] "[35m[1mGET /swaggerui/swagger-ui-standalone-preset.js HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 10:08:00] "[35m[1mGET /swaggerui/favicon-32x32.png HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 10:08:00] "[35m[1mGET /swaggerui/favicon-16x16.png HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 10:08:00] "[35m[1mGET /swaggerui/favicon-32x32.png HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 10:08:00] "[35m[1mGET /swaggerui/favicon-16x16.png HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 10:08:03] "[35m[1mGET /swaggerui/droid-sans.css HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 10:08:03] "[35m[1mGET /swaggerui/swagger-ui.css HTTP/1.1[0m" 500 -
DEBUG:root:This message should go to the log file
DEBUG:root:This message should go to the log file
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 10:37:06] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 10:37:06] "GET /swaggerui/droid-sans.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 10:37:06] "GET /swaggerui/swagger-ui.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 10:37:06] "GET /swaggerui/swagger-ui-standalone-preset.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 10:37:06] "GET /swaggerui/swagger-ui-bundle.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 10:37:06] "GET /swaggerui/favicon-32x32.png HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 10:37:06] "GET /swagger.json HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 10:37:15] "GET /faceCompare/hello HTTP/1.1" 200 -
DEBUG:root:This message should go to the log file
DEBUG:root:This message should go to the log file
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:05:31] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:05:31] "GET /swagger.json HTTP/1.1" 200 -
DEBUG:root:This message should go to the log file
DEBUG:root:This message should go to the log file
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:06:13] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:06:13] "GET /swagger.json HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:08:16] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:08:16] "GET /swaggerui/droid-sans.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:08:16] "GET /swaggerui/swagger-ui.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:08:16] "GET /swaggerui/swagger-ui-bundle.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:08:16] "GET /swaggerui/swagger-ui-standalone-preset.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:08:16] "GET /swaggerui/favicon-32x32.png HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:08:17] "GET /swagger.json HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:08:17] "GET /swaggerui/favicon-32x32.png HTTP/1.1" 200 -
DEBUG:root:This message should go to the log file
DEBUG:root:This message should go to the log file
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:09:10] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:09:10] "GET /swagger.json HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:09:21] "GET /swaggerui/swagger-ui-bundle.js.map HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:09:21] "GET /swaggerui/swagger-ui-standalone-preset.js.map HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:09:22] "GET /swaggerui/swagger-ui.css.map HTTP/1.1" 200 -
DEBUG:root:This message should go to the log file
DEBUG:root:This message should go to the log file
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:10:10] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:10:10] "GET /swagger.json HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:10:17] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:10:18] "GET /swaggerui/droid-sans.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:10:18] "GET /swaggerui/swagger-ui.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:10:18] "GET /swaggerui/swagger-ui-bundle.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:10:18] "GET /swaggerui/swagger-ui-standalone-preset.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:10:18] "GET /swaggerui/favicon-32x32.png HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:10:18] "GET /swagger.json HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:10:18] "GET /swaggerui/favicon-32x32.png HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:10:20] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:10:20] "GET /swagger.json HTTP/1.1" 200 -
INFO:werkzeug: * Detected change in 'E:\\Workspace\\face-compare\\controllers\\face_compare_controller.py', reloading
INFO:werkzeug: * Restarting with stat
DEBUG:root:This message should go to the log file
DEBUG:root:This message should go to the log file
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:11:30] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:11:30] "GET /swagger.json HTTP/1.1" 200 -
DEBUG:root:This message should go to the log file
DEBUG:root:This message should go to the log file
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:16:00] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:16:00] "GET /swagger.json HTTP/1.1" 200 -
DEBUG:root:This message should go to the log file
DEBUG:root:This message should go to the log file
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:16:47] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:16:47] "GET /swagger.json HTTP/1.1" 200 -
DEBUG:root:This message should go to the log file
DEBUG:root:This message should go to the log file
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:18:06] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:18:06] "GET /swagger.json HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:18:29] "POST /faceCompare/my-resource/1 HTTP/1.1" 403 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:18:40] "GET /faceCompare/my-resource/1 HTTP/1.1" 200 -
DEBUG:root:This message should go to the log file
DEBUG:root:This message should go to the log file
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:20:01] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:20:01] "GET /swagger.json HTTP/1.1" 200 -
DEBUG:root:This message should go to the log file
DEBUG:root:This message should go to the log file
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:22:47] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:22:47] "GET /swagger.json HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:22:58] "POST /face-compare/image/1 HTTP/1.1" 500 -
INFO:werkzeug: * Detected change in 'E:\\Workspace\\face-compare\\controllers\\face_compare_controller.py', reloading
DEBUG:root:This message should go to the log file
DEBUG:root:This message should go to the log file
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:23:29] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:23:29] "GET /swagger.json HTTP/1.1" 200 -
DEBUG:root:This message should go to the log file
DEBUG:root:This message should go to the log file
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:25:09] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:25:09] "GET /swagger.json HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:25:15] "POST /face-compare/image HTTP/1.1" 400 -
DEBUG:root:This message should go to the log file
DEBUG:root:This message should go to the log file
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:25:54] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:25:54] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:25:54] "GET /swagger.json HTTP/1.1" 200 -
INFO:werkzeug: * Detected change in 'E:\\Workspace\\face-compare\\controllers\\face_compare_controller.py', reloading
INFO:werkzeug: * Restarting with stat
DEBUG:root:This message should go to the log file
DEBUG:root:This message should go to the log file
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:27:04] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:27:04] "GET /swagger.json HTTP/1.1" 200 -
DEBUG:root:This message should go to the log file
DEBUG:root:This message should go to the log file
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:37:07] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:37:07] "GET /swaggerui/droid-sans.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:37:07] "GET /swaggerui/swagger-ui-bundle.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:37:07] "GET /swaggerui/swagger-ui.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:37:07] "GET /swaggerui/swagger-ui-standalone-preset.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:37:08] "GET /swaggerui/favicon-32x32.png HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:37:08] "GET /swagger.json HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:37:08] "GET /swaggerui/favicon-32x32.png HTTP/1.1" 200 -
INFO:werkzeug: * Detected change in 'E:\\Workspace\\face-compare\\controllers\\face_compare_controller.py', reloading
INFO:werkzeug: * Restarting with stat
DEBUG:root:This message should go to the log file
DEBUG:root:This message should go to the log file
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:58:22] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 11:58:22] "GET /swagger.json HTTP/1.1" 200 -
DEBUG:root:This message should go to the log file
DEBUG:root:This message should go to the log file
INFO:werkzeug: * Detected change in 'E:\\Workspace\\face-compare\\controllers\\face_compare_controller.py', reloading
INFO:werkzeug: * Restarting with stat
DEBUG:root:This message should go to the log file
DEBUG:root:This message should go to the log file
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 12:02:56] "GET / HTTP/1.1" 200 -
ERROR:flask_restx.api:Unable to render schema
Traceback (most recent call last):
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python38\lib\site-packages\flask_restx\api.py", line 571, in __schema__
    self._schema = Swagger(self).as_dict()
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python38\lib\site-packages\flask_restx\swagger.py", line 268, in as_dict
    "definitions": self.serialize_definitions() or None,
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python38\lib\site-packages\flask_restx\swagger.py", line 623, in serialize_definitions
    return dict(
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python38\lib\site-packages\flask_restx\swagger.py", line 624, in <genexpr>
    (name, model.__schema__)
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python38\lib\site-packages\flask_restx\model.py", line 76, in __schema__
    schema = self._schema
  File "C:\Users\Wilson\AppData\Local\Programs\Python\Python38\lib\site-packages\flask_restx\model.py", line 159, in _schema
    properties[name] = field.__schema__
AttributeError: 'decimal.Decimal' object has no attribute '__schema__'
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 12:02:56] "GET /swagger.json HTTP/1.1" 500 -
INFO:werkzeug: * Detected change in 'E:\\Workspace\\face-compare\\controllers\\face_compare_controller.py', reloading
INFO:werkzeug: * Restarting with stat
DEBUG:root:This message should go to the log file
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 12:03:48] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 12:03:48] "GET /swagger.json HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 12:04:02] "POST /face-compare/images HTTP/1.1" 500 -
DEBUG:root:This message should go to the log file
DEBUG:root:This message should go to the log file
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 12:05:24] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 12:05:24] "GET /swagger.json HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 12:05:31] "POST /face-compare/images HTTP/1.1" 500 -
DEBUG:root:This message should go to the log file
DEBUG:root:This message should go to the log file
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 12:10:09] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 12:10:09] "GET /swagger.json HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 12:12:42] "POST /face-compare/images HTTP/1.1" 500 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 12:13:00] "POST /face-compare/images HTTP/1.1" 500 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 12:13:15] "POST /face-compare/images HTTP/1.1" 500 -
DEBUG:root:This message should go to the log file
DEBUG:root:This message should go to the log file
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 12:13:56] "POST /face-compare/images HTTP/1.1" 400 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 12:14:18] "POST /face-compare/images HTTP/1.1" 400 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 12:14:19] "POST /face-compare/images HTTP/1.1" 400 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 12:14:20] "POST /face-compare/images HTTP/1.1" 400 -
INFO:werkzeug: * Detected change in 'E:\\Workspace\\face-compare\\controllers\\face_compare_controller.py', reloading
INFO:werkzeug: * Restarting with stat
DEBUG:root:This message should go to the log file
DEBUG:root:This message should go to the log file
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 12:15:35] "POST /face-compare/images HTTP/1.1" 400 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 12:15:37] "POST /face-compare/images HTTP/1.1" 400 -
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 12:15:37] "POST /face-compare/images HTTP/1.1" 400 -
DEBUG:root:This message should go to the log file
DEBUG:root:This message should go to the log file
INFO:werkzeug:127.0.0.1 - - [22/Apr/2022 12:16:41] "POST /face-compare/images HTTP/1.1" 200 -
